export const data1 = [
  {
    sno: 1,
    date: "12/12/2023",
    id: "Cell",
    name: "Sanika",
    phone: "+91 88088 XXXXX",
    course: "NID",
    area: "Mirzapur",
    platform: "Instagram",
    callbackdate: "21/12/2023",
    actions: "these are the actions",
  },
  {
    sno: 2,
    date: "12/12/2023",
    id: "Cell",
    name: "Sanika",
    phone: "+91 88088 XXXXX",
    course: "NID",
    area: "Mirzapur",
    platform: "Instagram",
    callbackdate: "21/12/2023",
    actions: "these are the actions",
  },
  {
    sno: 3,
    date: "12/12/2023",
    id: "Cell",
    name: "Sanika",
    phone: "+91 88088 XXXXX",
    course: "NID",
    area: "Mirzapur",
    platform: "Instagram",
    callbackdate: "21/12/2023",
    actions: "these are the actions",
  },
  {
    sno: 4,
    date: "12/12/2023",
    id: "Cell",
    name: "Sanika",
    phone: "+91 88088 XXXXX",
    course: "NID",
    area: "Mirzapur",
    platform: "Instagram",
    callbackdate: "21/12/2023",
    actions: "these are the actions",
  },
  {
    sno: 5,
    date: "12/12/2023",
    id: "Cell",
    name: "Sanika",
    phone: "+91 88088 XXXXX",
    course: "NID",
    area: "Mirzapur",
    platform: "Instagram",
    callbackdate: "21/12/2023",
    actions: "these are the actions",
  },
  {
    sno: 6,
    date: "12/12/2023",
    id: "Cell",
    name: "Sanika",
    phone: "+91 88088 XXXXX",
    course: "NID",
    area: "Mirzapur",
    platform: "Instagram",
    callbackdate: "21/12/2023",
    actions: "these are the actions",
  },
  {
    sno: 7,
    date: "12/12/2023",
    id: "Cell",
    name: "Sanika",
    phone: "+91 88088 XXXXX",
    course: "NID",
    area: "Mirzapur",
    platform: "Instagram",
    callbackdate: "21/12/2023",
    actions: "these are the actions",
  },
  {
    sno: 8,
    date: "12/12/2023",
    id: "Cell",
    name: "Sanika",
    phone: "+91 88088 XXXXX",
    course: "NID",
    area: "Mirzapur",
    platform: "Instagram",
    callbackdate: "21/12/2023",
    actions: "these are the actions",
  },
  {
    sno: 9,
    date: "12/12/2023",
    id: "Cell",
    name: "Sanika",
    phone: "+91 88088 XXXXX",
    course: "NID",
    area: "Mirzapur",
    platform: "Instagram",
    callbackdate: "21/12/2023",
    actions: "these are the actions",
  },
  {
    sno: 10,
    date: "12/12/2023",
    id: "Cell",
    name: "Sanika",
    phone: "+91 88088 XXXXX",
    course: "NID",
    area: "Mirzapur",
    platform: "Instagram",
    callbackdate: "21/12/2023",
    actions: "these are the actions",
  },
  {
    sno: 11,
    date: "12/12/2023",
    id: "Cell",
    name: "Sanika",
    phone: "+91 88088 XXXXX",
    course: "NID",
    area: "Mirzapur",
    platform: "Instagram",
    callbackdate: "21/12/2023",
    actions: "these are the actions",
  },
  {
    sno: 12,
    date: "12/12/2023",
    id: "Cell",
    name: "Sanika",
    phone: "+91 88088 XXXXX",
    course: "NID",
    area: "Mirzapur",
    platform: "Instagram",
    callbackdate: "21/12/2023",
    actions: "these are the actions",
  },
  {
    sno: 13,
    date: "12/12/2023",
    id: "Cell",
    name: "Sanika",
    phone: "+91 88088 XXXXX",
    course: "NID",
    area: "Mirzapur",
    platform: "Instagram",
    callbackdate: "21/12/2023",
    actions: "these are the actions",
  },
  {
    sno: 14,
    date: "12/12/2023",
    id: "Cell",
    name: "Sanika",
    phone: "+91 88088 XXXXX",
    course: "NID",
    area: "Mirzapur",
    platform: "Instagram",
    callbackdate: "21/12/2023",
    actions: "these are the actions",
  },
  {
    sno: 15,
    date: "12/12/2023",
    id: "Cell",
    name: "Sanika",
    phone: "+91 88088 XXXXX",
    course: "NID",
    area: "Mirzapur",
    platform: "Instagram",
    callbackdate: "21/12/2023",
    actions: "these are the actions",
  },
];
